# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build nbapp-backend`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t nbapp-backend`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system nbapp-backend && \
          adduser --system -G nbapp-backend nbapp-backend

COPY dist/nbapp-backend nbapp-backend/
RUN chown -R nbapp-backend:nbapp-backend .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix nbapp-backend --omit=dev -f install

CMD [ "node", "nbapp-backend" ]
